export const SPLIT_TYPES = {
  EQUAL: "EQUAL",
  EXACT: "EXACT",
  PERCENTAGE: "PERCENTAGE",
  SHARES: "SHARES",
};

export const CURRENCIES = {
  INR: "INR",
  USD: "USD",
};

export const EXCHANGE_RATES = {
  USD_TO_INR: 83.0,
};

export const ANOMALY_TYPES = {
  DUPLICATE: "DUPLICATE",
  NEGATIVE_AMOUNT: "NEGATIVE_AMOUNT",
  INVALID_SPLIT: "INVALID_SPLIT",
  CURRENCY_MISMATCH: "CURRENCY_MISMATCH",
  MEMBER_NOT_IN_GROUP: "MEMBER_NOT_IN_GROUP",
  SETTLEMENT_AS_EXPENSE: "SETTLEMENT_AS_EXPENSE",
  INVALID_DATE: "INVALID_DATE",
  MISSING_FIELDS: "MISSING_FIELDS",
  AMOUNT_MISMATCH: "AMOUNT_MISMATCH",
  INVALID_PERCENTAGE: "INVALID_PERCENTAGE",
  MEMBER_LEFT_BEFORE_EXPENSE: "MEMBER_LEFT_BEFORE_EXPENSE",
  INCONSISTENT_FORMAT: "INCONSISTENT_FORMAT",
};

export const ANOMALY_ACTIONS = {
  SKIP: "SKIP",
  IMPORT: "IMPORT",
  IMPORT_WITH_CORRECTION: "IMPORT_WITH_CORRECTION",
  MERGE: "MERGE",
  REQUIRE_APPROVAL: "REQUIRE_APPROVAL",
};
